// Запрос список активностей
    http://localhost:3000/activity/;
###
//Создание активности
POST http://localhost:3000/activity
Content-Type: application/json

{
  "name": "Тест",
  "description": "Некоторое описание",
  "type": "excursion",
  "location": "Moscow",
  "image": "https://blog.pshares.org/wp-content/uploads/sites/10/2012/02/dawn-dusk-hd-wallpaper-36717-1536x956.jpg",
  "slug": "example"
}
###
